import { defineStore } from "pinia";

export const useMainStore = defineStore("main", {
  state: () => ({
    activeMenu: "home",
    darkTheme: false,
    projects: [
      {
        id: 1,
        name: "ezofis Enterprise",
        description: {
          short: "SaaS platform for Enterprise Content Management.",
          long: "ezofis Enterprise is a SaaS platform for Enterprise Content Management (ECM). Enterprise content management (ECM) — sometimes referred to as document management or records management — is the process of managing the entire lifecycle of an organization's content, including documents, spreadsheets, contracts and scanned images. The goal of an ECM solution is to reduce risk and improve productivity, efficiency and customer experience by eliminating paper-based tasks and enhancing process visibility.",
        },
        technologies: [
          "HTML",
          "CSS",
          "Sass",
          "JavaScript (ES6+)",
          "Vue.js",
          "Quasar.js",
          "Axios.js",
          "Vuex",
          "VueRouter",
          "Vee-Validate",
          "Fabric.js",
          "Crypto.js",
          "Lodash.js",
          "Day.js",
        ],
        link: "http://52.172.32.88/ezofis-web/",
        repository: "",
        screenshotsCount: 34,
        type: "WEB",
      },
      {
        id: 2,
        name: "ezofis Business",
        description: {
          short: "SaaS platform for Document Management System.",
          long: "ezofis Business is a SaaS platform for Document Management System (DMS). A document management system (DMS) is a software solution that enables an organization to automate the creation, storage, tracking and retrieval of its electronic documents within a single database platform. It's designed to maximize the efficient modification, digitization, filing and accessing of documents and images. DMS is the less advanced version of enterprise content management (ECM).",
        },
        technologies: [
          "HTML",
          "CSS",
          "JavaScript (ES6+)",
          "Vue.js",
          "Quasar.js",
          "Axios.js",
          "Vuex",
          "VueRouter",
          "Vuelidate",
          "Konva.js",
          "Date-fns",
        ],
        link: "https://cloud.ezofis.com/EZOFISSEARCH/signin",
        repository: "",
        screenshotsCount: 22,
        type: "WEB",
      },
      {
        id: 3,
        name: "ezofis Business Mobile",
        description: {
          short: "Mobile version of the ezofis Business web application.",
          long: "ezofis Business Mobile is the mobile version of the ezofis Business web application.",
        },
        technologies: ["Dart", "Flutter", "GetX", "Dio", "Material Design"],
        link: "https://play.google.com/store/apps/details?id=com.ezofis.ezofis_mobile",
        repository: "",
        screenshotsCount: 21,
        type: "MOBILE",
      },
      {
        id: 4,
        name: "ezofis Business v2 Prototype 1",
        description: {
          short: "Prototype v1 of the ezofis Business app.",
          long: "Prototype v1 of the ezofis Business app.",
        },
        technologies: [
          "HTML",
          "CSS",
          "Sass",
          "JavaScript (ES6+)",
          "Vue.js",
          "Quasar.js",
          "Konva.js",
        ],
        link: "https://ezofis-business-p1.netlify.app",
        repository: "",
        screenshotsCount: 24,
        type: "WEB",
      },
      {
        id: 5,
        name: "ezofis Business v2 Prototype 2",
        description: {
          short: "Prototype v2 of the ezofis Business app.",
          long: "Prototype v2 of the ezofis Business app.",
        },
        technologies: [
          "HTML",
          "CSS",
          "Sass",
          "JavaScript (ES6+)",
          "Vue.js",
          "Quasar.js",
          "Konva.js",
        ],
        link: "https://ezofis-business-p2.netlify.app",
        repository: "",
        screenshotsCount: 32,
        type: "WEB",
      },
      {
        id: 6,
        name: "Eterno Forms",
        description: {
          short: "Form builder prototype.",
          long: "Eterno Forms is a feature-rich web application for creating and managing forms.",
        },
        technologies: [
          "HTML",
          "CSS",
          "JavaScript (ES6+)",
          "Vue.js",
          "Quasar.js",
          "Chart.js",
        ],
        link: "https://eterno-forms.netlify.app/",
        repository: "https://github.com/charlesvinoth/eterno-forms",
        screenshotsCount: 12,
        type: "WEB",
      },
      {
        id: 7,
        name: "Sathiyam Oils",
        description: {
          short: "eCommerce mobile app for cold pressed oils.",
          long: "eCommerce mobile app for cold pressed oils.",
        },
        technologies: ["Dart", "Flutter", "GetX", "Dio", "Material Design"],
        link: "https://play.google.com/store/apps/details?id=com.sathiyam.sathiyam",
        repository: "",
        screenshotsCount: 13,
        type: "MOBILE",
      },
      {
        id: 8,
        name: "ezofis Design System",
        description: {
          short: "Reusable components and patterns library.",
          long: "ezofis Design System is a complete set of standards intended to manage design at scale using reusable components and patterns.",
        },
        technologies: [
          "HTML",
          "CSS",
          "JavaScript (ES6+)",
          "Vue.js",
          "Quasar.js",
        ],
        link: "https://ezofis-design-system.netlify.app/Components/Button",
        repository: "https://github.com/charlesvinoth/ezofis-design-system",
        screenshotsCount: 18,
        type: "WEB",
      },
      {
        id: 9,
        name: "Miscellaneous",
        description: {
          short: "Screenshots from various applications and prototypes.",
          long: "Screenshots from various applications and prototypes, that I have worked.",
        },
        technologies: [
          "HTML",
          "CSS",
          "JavaScript (ES6+)",
          "Vue.js",
          "Quasar.js",
          "Dart",
          "Flutter",
          "GetX",
          "Dio",
          "Material Design",
        ],
        link: "",
        repository: "",
        screenshotsCount: 20,
        type: "WEB",
      },
    ],
    experience: [
      {
        id: 1,
        jobTitle: "senior front-end developer",
        company: "ezofis",
        period: "sep 2021 - present",
        roles: [
          "Designed and built modern, scalable, responsive, distributed cloud-based applications using Vue.js and React.js.",
          "Delivered complex UX/UI components without compromising quality and speed.",
          "Led a team of 4 developers through building multiple Vue.js and React.js applications.",
          "Built and shipped 2 robust apps to Android/iOS devices using Dart and Flutter.",
          "Followed SDLC best practices within an Agile environment to produce rapid iterations for clients.",
          "Experienced in working with IIS web servers, Netlify and Azure, and Firebase.",
          "Collaborated with developers, managers, and clients during development processes to confirm proposals and design best practices.",
        ],

        isCollapsed: false,
      },
      {
        id: 2,
        jobTitle: "front-end developer",
        company: "ezofis",
        period: "sep 2019 - aug 2021",
        roles: [
          "Conceptualized, designed, and developed several apps using React.js, Vue.js, etc.",
          "Crafted a solid design system to enforce consistency across the application. ",
          "Translated designs and wireframes into a highly responsive user interface and reusable components.",
          "Performed user experience and quality assurance testing to identify and remedy shortcomings.",
          "Introduced and enforced healthy codebases, coding styles, and standards.",
          "Interfaced with clients every week, providing technological expertise and knowledge.",
          "Analyzed business requirements, and participated in technical design, development, and testing of various modules assigned.",
        ],
        isCollapsed: true,
      },
      {
        id: 3,
        jobTitle: "junior front-end developer",
        company: "ezofis",
        period: "nov 2018 - aug 2019",
        roles: [
          "Written modern, performant, and robust code for a diverse array of clients and internal projects.",
          "Made recommendations for new technology integration based on suitability and alignment with business goals.",
          "Removed jQuery and jQuery plugins and replaced them with vanilla JavaScript, which increased the application speed by 50%.",
          "Communicated effectively with project managers and the team to complete projects on time and deliver to clients accordingly.",
          "Introduced and used Git and GitHub to manage the source code.",
          "Replaced XML with JSON as API payload which increased the application speed by 20%.",
        ],
        isCollapsed: true,
      },
      {
        id: 4,
        jobTitle: "front-end developer trainee",
        company: "ezofis",
        period: "apr 2018 - oct 2018",
        roles: [
          "Worked on major bug fixes, which included UI issues and functionality issues as well.",
          "Involved in web designing using HTML, CSS, and JavaScript and extensively used CSS Flexbox for positioning.",
          "Validated 100% of user input before submitting to the back-end.",
          "Developed page layouts, navigations and presented designs and concepts to the clients and the management review.",
          "Coded using HTML, CSS and JavaScript to develop features for both mobile and desktop platforms.",
          "Designed and updated layouts to meet usability and performance requirements.",
          "Contributed to projects within Scrum project management environments.",
          "Created plans and communicated deadlines to complete tasks on time.",
          "Collaborated with team members to achieve target results.",
          "Used critical thinking to break down problems, evaluate solutions and make decisions.",
        ],
        isCollapsed: true,
      },
    ],
  }),

  actions: {
    setActiveMenu(menu) {
      this.activeMenu = menu;
    },

    toggleTheme() {
      const html = document.querySelector("html");
      html.classList.remove(this.darkTheme ? "dark" : "light");
      html.classList.add(this.darkTheme ? "light" : "dark");

      this.darkTheme = !this.darkTheme;
    },
  },
});
